### ISSUE TITLE
WCT errors out on Firefox

### ISSUE THREAD

**Issue by madeleineostoja** [SimplaElements/simpla-link#1]
With this: 

```sh
Tests failed: Error thrown outside of test function: document.getElementById(...).create is not a function
```

Reading around seems there were a few old issues with Polymer's `test-fixture` not upgrading in time that used to cause this, but was apparently fixed ages ago. Similar issues with user elements using test-fixture, like simpla-admin.

**Comment by bedeoverend** [comment]
I'm assuming you're talking about https://github.com/Polymer/web-component-tester/issues/505? Looked at the commit that fixed it, and looks like that commit was included in the 6.0.0 pre-release, which means 5.0/4.0 that we're using won't get it I'd say. I've gotten similar issues with `.restore` is not a function, usually re-running the tests in travis will help. Super annoying though.
